version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_KEY=base64:iJIPk+b6urfj3DtaxcIFnQfuKLFFjHreb70EbpVHCog=
            - DB_CONNECTION=sqlite

    node:
        image: node:21.2
        container_name: laravel_node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - node_modules:/usr/src/app/node_modules
        command: >
            bash -c "yarn global add vite && yarn run production"
volumes:
    node_modules:
