version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        volumes:
            - .:/var/www
            - ./public/cv/uploads:/var/www/public/cv/uploads
            - ./public/images/icons:/var/www/public/images/icons
            - ./public/images/uploads:/var/www/public/images/uploads
        networks:
            - app-network

    web:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
